{{- $token := .Values.agent.token | required ".Values.agent.token is required."}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vantage-kubernetes-agent.fullname" . }}
  labels:
    {{- include "vantage-kubernetes-agent.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ $token | b64enc | quote }}
