apiVersion: v1
kind: Service
metadata:
  name: { { include "vantage-kubernetes-agent.fullname" . } }
  namespace: { { .Release.Namespace } }
  labels: { { - include "vantage-kubernetes-agent.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.name } }
      protocol: TCP
      name: { { .Values.service.name } }
  selector:
    { { - include "vantage-kubernetes-agent.selectorLabels" . | nindent 4 } }
